config/routes.rb
Rails.application.routes.draw do
  resources :medications do
    member do
      resources :dosages
    end
  end

  root 'medications#index'

end

app/models/dosage.rb
class Dosage < ActiveRecord::Base
  validates :value, presence: true
  validates :unit, presence: true
  belongs_to :medication
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  validates :name,  presence: true,
                    uniqueness: { case_sensitive: false }
  validates :category, presence: true
  has_many :dosages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dosages_controller.rb
class DosagesController < ApplicationController

  # before_action :set_dosage, only: [:show, :edit, :update, :destroy]
  before_action :set_medication, only: [:index, :create]
  before_action :set_dosage, only: [:destroy]

  # GET medications/1/dosages
  # GET medications/1/dosages.json
  def index
    @dosages = @medication.dosages
    respond_to do |format|
      format.html {render :index}
      format.json {render json: {medication: @medication, dosages: @dosages}}
    end
  end

  def create
    @dosage = @medication.dosages.create(dosage_params)
    redirect_to edit_medication_path(@medication)
  end

  def destroy
    @medication = @dosage.medication
    @dosage.destroy
    redirect_to edit_medication_path(@medication)
  end

  private

  def set_medication
    @medication = Medication.find(params[:id])
  end


  def set_dosage
    @dosage = Dosage.find(params[:id])
  end

  def dosage_params
    params.require(:dosage).permit(:value, :unit)
  end

end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_action :set_medication, only: [:show, :edit, :update, :destroy]

  # GET /medications
  # GET /medications.json
  def index
    @medications = Medication.all
  end

  # GET /medications/1
  # GET /medications/1.json
  def show
  end

  # GET /medications/new
  def new
    @medication = Medication.new
  end

  # GET /medications/1/edit
  def edit
    @dosage = @medication.dosages.new
  end

  # POST /medications
  # POST /medications.json
  def create
    @medication = Medication.new(medication_params)

    respond_to do |format|
      if @medication.save
        format.html { redirect_to @medication, notice: 'Medication was successfully created.' }
        format.json { render :show, status: :created, location: @medication }
      else
        format.html { render :new }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medications/1
  # PATCH/PUT /medications/1.json
  def update
    respond_to do |format|
      if @medication.update(medication_params)
        format.html { redirect_to @medication, notice: 'Medication was successfully updated.' }
        format.json { render :show, status: :ok, location: @medication }
      else
        format.html { render :edit }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    @medication.destroy
    respond_to do |format|
      format.html { redirect_to medications_url, notice: 'Medication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medication
      @medication = Medication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medication_params
      params.require(:medication).permit(:name, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdhdTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="box bottom-buffer">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :category %><br>
      <%= f.select(:category) do %>
        <%= content_tag(:option, "Stimulants") %>
        <%= content_tag(:option, "Non-Stimulants") %>
        <%= content_tag(:option, "Antidepressants") %>
      <% end %>
    </div>

    <div class="actions">
      <button class="btn" type="submit">
        Save Medication
      </button>
    </div>
  </div>
<% end %>

<%- if @dosage %>
  <%= form_for(@dosage) do |d| %>
    <div class="box">
      <div class="field">
        <h4>Dosages:</h4>
        <div>
          <%- if @medication.dosages.count > 0 %>
            <% @medication.dosages.each do |dosage| %>
              <%- if dosage.value %>
                <%= "#{dosage.value}#{dosage.unit}" %>
                <%= link_to 'Destroy', dosage, method: :delete %><br>
              <% end %>
            <% end %>
          <% else %>
            No dosages added yet
          <% end %>
        </div>
        <h4>Add a dosage:</h4>
        <div class="field">
          <%= d.label :value %><br>
          <%= d.text_field(:value) %>
        </div>
        <div class="field">
          <%= d.label :unit %><br>
          <%= d.select(:unit) do %>
            <%= content_tag(:option, "g (grams)", value: "g") %>
            <%= content_tag(:option, "mg (milligrams)", value: "mg") %>
            <%= content_tag(:option, "ml (milliliters)", value: "ml") %>
          <% end %>
        </div>
      </div>
      <div class="actions">
        <button class="btn" type="submit">Add dosage</button>
      </div>
    </div>
  <% end %>
<% end %>


<div>
  <h2><a href="http://www.healthline.com/health/adhd/medication-list#Non-Stimulants3">Stimulants:</a></h2>
  <p>Stimulants are the most commonly prescribed medications for ADHD. You might hear this class of drug referred to as central nervous stimulant (CNS) medications. Stimulants increase dopamine and norepinephrine in the brain to improve concentration while also decreasing fatigue. Stimulants are often the first course of medications used for ADHD treatment.</p>
</div>

<div>
  <h2><a href="http://www.healthline.com/health/adhd/medication-list#Non-Stimulants3">Non-Stimulants:</a></h2>
  <p>Non-stimulants affect the brain differently than stimulants. Though these drugs affect neurotransmitters, they don’t increase dopamine levels. It also generally takes longer to see results. Non-stimulants come in a variety of classes. They might be used when stimulants prove unsafe, ineffective, or for a person who wants to avoid side effects of stimulants.</p>
</div>

<div>
  <h2><a href="http://www.healthline.com/health/adhd/medication-list#Non-Stimulants3">Antidepressants:</a></h2>
  <p>Antidepressants are not FDA-approved to treat ADHD, although some patients may have complex diagnoses and they may be prescribed these drugs along with ADHD medications.</p>
</div>

<br>
<br>

app/views/medications/edit.html.erb
<h1>Editing Medication</h1>

<%= render 'form' %>

<%= link_to 'Show', @medication %> |
<%= link_to 'Back', medications_path %>

app/views/medications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Medications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Dosages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medications.each do |medication| %>
      <tr>
        <td><%= medication.name %></td>
        <td><%= medication.category %></td>
        <td>
          <%- if medication.dosages.size > 0 %>
            [<% medication.dosages.each do |dosage| %>
              <%= "#{dosage.value} #{dosage.unit}, " %>
            <% end %>]
          <%- else %>
            No dosages
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_medication_path(medication) %></td>
        <td><%= link_to 'Destroy', medication, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Medication', new_medication_path %>

app/views/medications/new.html.erb
<h1>New Medication</h1>

<%= render 'form' %>

<%= link_to 'Back', medications_path %>

app/views/medications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medication.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @medication.category %>
</p>

<%= link_to 'Edit', edit_medication_path(@medication) %> |
<%= link_to 'Back', medications_path %>